global:
  http_config:
    tls_config:
      insecure_skip_verify: true

route:
  receiver: 'ceph-dashboard'
  group_wait: 1m
  group_interval: 1m
  repeat_interval: 1m

receivers:
  - name: 'ceph-dashboard'
    webhook_configs:
    - url: 'https://localhost:4200/api/prometheus_receiver'
    - url: 'http://localhost:9099/'
