version: '3'

services:
  node-exporter:
    user: 'root'
    image: 'quay.io/prometheus/node-exporter'
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/rootfs:ro'
    network_mode: 'host'
    command: ['--path.procfs', '/host/proc',
              '--path.sysfs', '/host/sys',
              '--collector.filesystem.ignored-mount-points', '^/(sys|proc|dev|host|etc)($$|/)']
  prometheus:
    image: 'quay.io/prometheus/prometheus'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml:ro'
    container_name: 'prometheus'
    network_mode: 'host'

  grafana:
    image: 'grafana/grafana'
    container_name: 'grafana'
    network_mode: 'host'
    volumes:
      - './grafana.ini:/etc/grafana/grafana.ini:ro'

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: H2
    ports:
      - "8080:8080"

  openldap:
    image: osixia/openldap:1.2.0
    environment:
      LDAP_TLS_VERIFY_CLIENT: try
    ports:
      - "2389:389"

  phpldapadmin:
    image: osixia/phpldapadmin:0.7.1
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
    ports:
      - "90:443"
    links:
      - openldap

  shibboleth:
    build:
      context: ./shibboleth
      dockerfile: Dockerfile
    ports:
      - "9080:9080"
      - "9443:9443"
    links:
      - openldap

  iscsi1:
    build:
      context: ./iscsi
      dockerfile: Dockerfile
      #ports:
      #- "3260:3260"
        #- "5000:5000"
        #network_mode: 'host'
    hostname: "ceph-gw-1"
    extra_hosts:
      ceph-gw-2: 172.18.0.2
    cap_add:
      - 'ALL'
    privileged: true
    links:
      - iscsi2
    volumes:
      - '../ceph:/ceph'
      - '/dev:/dev'
      - '/run/systemd/journal:/run/systemd/journal'
      - '/lib/modules:/lib/modules'

  iscsi2:
    build:
      context: ./iscsi
      dockerfile: Dockerfile
    #ports:
      #- "3260:3260"
      #- "5000:5000"
    #network_mode: 'host'
    hostname: "ceph-gw-2"
    extra_hosts:
      ceph-gw-1: 172.18.0.3
    cap_add:
      - 'ALL'
    privileged: true
    volumes:
      - '../ceph:/ceph'
      - '/dev:/dev'
      - '/run/systemd/journal:/run/systemd/journal'
      - '/lib/modules:/lib/modules'

